### ISSUE TITLE
Frame is not being set correctly.

### ISSUE THREAD

**Issue by egzonpllana** [tallhasarwar/TSBlurEffectView#1]
If you use it with a storyboard, or even without the storyboard and you set the blur through a viewDidLoad or viewWillAppear, the frame of the blur view will be incorrect. To fix it, we should do two improvements:

1. Override the layoutSubviews method: Instead of setting the frame in didMoveToSuperview, override the layoutSubviews method to update the frame whenever the superview's layout changes. This will ensure that the blurred view always has the correct frame.

```
override func layoutSubviews() {
    super.layoutSubviews()
    frame = superview?.bounds ?? CGRect.zero
    setupBlur()
}
```

2. Update the didMoveToSuperview method: Since the frame setting logic is moved to layoutSubviews, you can simplify the didMoveToSuperview method by removing the frame assignment.

```
override func didMoveToSuperview() {
    super.didMoveToSuperview()
    backgroundColor = .clear
    setupBlur()
}
```

**Comment by tallhasarwar** [comment]
Hey Man thanks for highlighting the issue. I'll update and commit. Thanks Again
